### ISSUE TITLE
Love your themes! however,

### ISSUE THREAD

**Issue by MangoChocobo** [doki-theme/doki-theme-hyper#35]
Hey, I want to preface this by saying I do truly love your themes. I am a huge fan of Highschool DxD however i'm not a big fan of the bright red for my editors so i always found myself editing it to have a dark theme but have my rias sticker out. I just can't seem to find where to do this for my Hyper terminal at all. I have it edited for my VScode, but hyper has me puzzled.

**Comment by Unthrottled** [comment]
:thinking: 

Hmm, so you should have a `~/.hyper.js` file (if on mac or linux) [this should help with windows](https://github.com/vercel/hyper/issues/1134#issuecomment-493288638)

You can edit the `css` property in the file

This should give you an idea on what needs to be customized
https://github.com/doki-theme/doki-theme-hyper/blob/be29451f076e5904ad25b4d0639fe4d171292ea3/src/css.ts#L54

![image](https://user-images.githubusercontent.com/15972415/111227842-2f0cb680-85b1-11eb-9072-5fa9fee0d618.png)

I'll close this once I've added documentation in the readme on this. Thanks for your interest!

**Comment by MangoChocobo** [comment]
Thanks!, I did find it by doing the most roundabout way I believe possible and that was by editing the "DokiThemeDefinitions.js" file. probably the most uncouth way, but it worked!
