### ISSUE TITLE
On windows version doki-theme-hyper menu doesn't show despite plugin beeing installed.

### ISSUE THREAD

**Issue by vilchyyy** [doki-theme/doki-theme-hyper#57]
![image](https://user-images.githubusercontent.com/73382020/148040954-eaba83e2-d765-48dd-b3e3-e4e709d1f1f2.png)

**Comment by Unthrottled** [comment]
That's weird, does it not show up after you close all of the hyper windows, and open it back up?

If that doesn't work could you open up the developer tools and see if there is any barf in the console, please?

https://user-images.githubusercontent.com/15972415/148070393-e7bb2bfd-1b87-4eb4-882d-77e347936ebb.mp4

**Comment by vilchyyy** [comment]
![image](https://user-images.githubusercontent.com/73382020/148700114-e2b4b2e6-bd72-484c-b44a-d57fb5c2d1af.png)

This is the only thing that shows. On my linux dualboot plugin works flawlessly.

**Comment by Unthrottled** [comment]
That's curious.

What does your `%USERPROFILE%\AppData\Roaming\Hyper\.hyper_plugins\node_modules` look like?

![image](https://user-images.githubusercontent.com/15972415/148701766-2dd95396-8ea6-4c44-86bb-e0325b516a08.png)


Also does your `.hyper.js` config file have `doki-theme-hyper` as a plugin?

https://user-images.githubusercontent.com/15972415/148701840-92d6cff7-8bfb-470f-be9a-c2dbd03b7992.mp4

**Comment by vilchyyy** [comment]
1. There is no such folder in .hyper_plugins as node_modules
![image](https://user-images.githubusercontent.com/73382020/148702114-1476c3cb-f19c-412d-bd24-0b8fc2d2cb0c.png)
2. .hyper.js has doki-theme-hyper as a plugin

**Comment by Unthrottled** [comment]
What does the content's of the `package.json` look like?

If it looks like this
```
{
  "name": "hyper-plugins",
  "description": "Auto-generated from `~/.hyper.js`!",
  "private": true,
  "version": "0.0.1",
  "repository": "vercel/hyper",
  "license": "MIT",
  "homepage": "https://hyper.is",
  "dependencies": {
    "doki-theme-hyper": "latest"
  }
}
```

Try running `npm install` in the ` .hyper_plugins` directory.

https://user-images.githubusercontent.com/15972415/148702756-bd45bc11-cd96-44ab-b5b9-c66f1623d488.mp4

Part of me wonders if something is hijacking the `hyper` command, and it is installing the plugin in an unexpected area.

**Comment by Unthrottled** [comment]
I'll assume you've either figured your issue out or stopped caring.

If you need anymore help, just let me know, thanks!

**Comment by NOPR9D** [comment]
> That's curious.
> 
> What does your `%USERPROFILE%\AppData\Roaming\Hyper\.hyper_plugins\node_modules` look like?
> 
> ![image](https://user-images.githubusercontent.com/15972415/148701766-2dd95396-8ea6-4c44-86bb-e0325b516a08.png)
> 
> Also does your `.hyper.js` config file have `doki-theme-hyper` as a plugin?
> bandicam.2022-01-09.15-33-22-837.mp4

Got same issue, and this fix my probleme. Thanks !
