### ISSUE TITLE
Rikka theme missing

### ISSUE THREAD

**Issue by marnixah** [doki-theme/doki-theme-hyper#73]
Does more work need to be done for support, or just build again?

If more work needs to be done and I can be of any assistance, feel free to mention it

**Comment by marnixah** [comment]
(this issue also applies to https://github.com/doki-theme/doki-theme-vim)

**Comment by Unthrottled** [comment]
Ah, For whatever reason she's under `Takanashi Rikka` (I forget why I started with full names with last starting first, think it was Hatsune Miku that started it)

<img width="542" alt="Screen Shot 2022-10-13 at 4 10 09 PM" src="https://user-images.githubusercontent.com/15972415/195711509-4d9c8eef-4efc-4a3d-b0a6-fdb8908d37ac.png">

<img width="295" alt="Screen Shot 2022-10-13 at 4 11 01 PM" src="https://user-images.githubusercontent.com/15972415/195711516-09ebce4e-58f8-48bd-9dc2-3ff48f95e9ca.png">

This is on `v88.1-1.1.0`. Please verify, thanks!

<img width="1020" alt="Screen Shot 2022-10-13 at 4 14 43 PM" src="https://user-images.githubusercontent.com/15972415/195712039-ce6dc39d-831b-45b6-a6d9-7a3c5e5521be.png">

**Comment by marnixah** [comment]
Can verify it works, guess I just looked over it. Thank you very much!
